language: go
sudo: false
install:
- go install -v ./vendor/github.com/go-swagger/go-swagger/cmd/swagger
- go install -v ./vendor/github.com/jteeuwen/go-bindata/...
- go install -v ./vendor/github.com/mailru/easyjson/...
- go generate -x .
script:
- go build .
